site_name: Derelict Documentation
site_url: http://derelictorg.github.io
repo_url: https://github.com/DerelictOrg
site_description: Documentation for the Derelict project, a collectiion of D bindings to C libraries commonly used in game development.
site_author: Mike Parker
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - codehilite(css_class=code)
pages:
  - 'Introduction' : 'index.md'
  - 'Support' : 'support.md'
  - 'Overview' : 'overview.md'
  - 'About Bindings' : 'bindings.md'
  - 'Compiling and Linking' :
    - 'Overview' : 'building/overview.md'
    - 'When Managing Projects with DUB' : 'building/with-dub.md'
    - 'When Managing Projects without DUB' : 'building/without-dub.md'
  - 'Loading Shared Libraries' :
    - 'The Derelict Loader' : 'loading/loader.md'
    - 'Load Failures' : 'loading/failure.md'