site_name: Derelict Documentation
site_url: http://derelictorg.github.io
repo_url: https://github.com/DerelictOrg
edit_uri: derelictorg.github.io/edit/mkdocs/docs
site_description: Documentation for the Derelict project, a collectiion of D bindings to C libraries commonly used in game development.
site_author: Mike Parker
theme: material
markdown_extensions:
  - codehilite(guess_lang=false)
  - toc:
      permalink: true
  - admonition
pages:
  - 'Introduction' : 'index.md'
  - 'Support' : 'support.md'
  - 'Overview' : 'overview.md'
  - 'About Bindings' : 'bindings.md'
  - 'Compiling and Linking' :
    - 'Overview' : 'building/overview.md'
    - 'With DUB Projects' : 'building/with-dub.md'
    - 'With Non-DUB Projects' : 'building/without-dub.md'
    - 'Compiling on Windows' : 'building/windows.md'
  - 'Loading Shared Libraries' :
    - 'The Derelict Loader' : 'loading/loader.md'
    - 'Load Failures' : 'loading/failure.md'
  - 'Packages' :
    - 'Latest Versions': 'packages/latest-versions.md'
    - 'DerelictGL3': 'packages/gl3.md'
    - 'DerelictGLFW3': 'packages/glfw3.md'
    - 'DerelictSDL2': 'packages/sdl2.md'
    - 'DerelictSFML2': 'packages/sfml2.md'
